
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# device tracker configuration
device_tracker: !include device_tracker.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml