#   author: thibault@desaules.me
#   contributor: none
#   licence: Apache License, Version 2.0 (https://opensource.org/licenses/Apache-2.0)
#   example:
#     docker-compose --file /mnt/c/Users/tdesa/GitHub/domotique/docker-compose.yml up
#     docker-compose --file /mnt/c/Users/tdesa/GitHub/domotique/docker-compose.yml up --detach --remove-orphans --force-recreate
#     docker-compose --file /mnt/c/Users/tdesa/GitHub/domotique/docker-compose.yml down
---
version: '3'

services:
  vernemq:
    container_name: 'vernemq'
    build: ./vernemq
    restart: 'no'
    image: 'ghcr.io/tdesaules/vernemq-1.12.14-alpine3.15:1.0.0'
    networks:
      development:
    dns: '172.16.254.253'
    ports:
      - '1883:1883'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - './etc:/opt/vernemq/etc'
  zigbee2mqtt:
    container_name: 'zigbee2mqtt'
    restart: 'no'
    image: 'ghcr.io/tdesaules/zigbee2mqtt-1.24.0-alpine3.15:1.0.0'
    networks:
      development:
    dns: '172.16.254.253'
    ports:
      - '8080:8080'
    devices:
      - '/dev/ttyUSB0:/dev/ttyUSB0'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - './data:/opt/zigbee2mqtt/data'
  homeassistant:
    container_name: 'homeassistant'
    build: ./homeassistant
    restart: 'no'
    image: 'homeassistant'
    networks:
      development:
    dns: '172.16.254.253'
    ports:
      - '8123:8123'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - './config:/home/homeassistant/.homeassistant' 

networks:
  development:
    external: true
...
